# Generated by Django 2.0.2 on 2018-02-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_team_members',
            field=models.IntegerField(default=1),
        ),
    ]
