# Generated by Django 2.0.2 on 2018-02-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180207_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_to_be_paid',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=5),
        ),
    ]
