# Generated by Django 2.0.2 on 2018-02-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180207_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_of_team_members',
            field=models.IntegerField(default=0),
        ),
    ]
