# Generated by Django 2.0.2 on 2018-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180211_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hosp',
            field=models.BooleanField(default=False),
        ),
    ]
