# Generated by Django 2.0.2 on 2018-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_profile_is_hosp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_mode',
            field=models.CharField(default='Online', max_length=10),
        ),
    ]
