# Generated by Django 2.0.2 on 2018-02-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_profile_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_paid',
            field=models.IntegerField(default=0),
        ),
    ]
