# Generated by Django 2.0.2 on 2018-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180216_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_to_be_paid',
            field=models.IntegerField(default=250),
        ),
    ]
