# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('institute', models.CharField(max_length=500)),
                ('event', multiselectfield.db.fields.MultiSelectField(choices=[('Hack D Unhackd', 'Hack D Unhackd'), ('Appiness', 'Appiness'), ('Game of Codes', 'Game of Codes'), ('Wolf of Web street', 'Wolf of Web street'), ('Robo Dangal', 'Robo Dangal'), ('Dizhard', 'Dizhard'), ('Flying Syndrone', 'Flying Syndrone'), ('Robo Soccer', 'Robo Soccer'), ('Enkindle', 'Enkindle'), ('Questa', 'Questa'), ('Lan Gaming', 'Lan Gaming'), ('Treasure Hunt', 'Treasure Hunt'), ('Nukkad Natak', 'Nukkad Natak'), ('Dance Fever', 'Dance Fever')], max_length=170)),
                ('accomodation_days', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtotal', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.Profile'),
        ),
    ]
