# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180227_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='event',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Appiness', 'Appiness'), ('Backyard Data Science', 'Backyard Data Science'), ('Game of Codes', 'Game of Codes'), ('Wolf of Web street', 'Wolf of Web street'), ('Robo Dangal', 'Robo Dangal'), ('Dizhard', 'Dizhard'), ('Flying SynDRONE', 'Flying SynDRONE'), ('Robo Soccer', 'Robo Soccer'), ('Enkindle', 'Enkindle'), ('Questa', 'Questa'), ('Gamers Crusade/LAN Gaming', 'Gamers Crusade/LAN Gaming'), ('Treasure Hunt', 'Treasure Hunt'), ('Nukkad Natak', 'Nukkad Natak'), ('Dance Fever', 'Dance Fever'), ('Capriccio/Singing', 'Capriccio/Singing')], max_length=210),
        ),
        migrations.AlterField(
            model_name='member',
            name='total',
            field=models.IntegerField(default=250),
        ),
    ]
